configName: 1PP - Flip
createdAt: 2026-04-23 15:35:05
lastModified: 2026-07-14 15:06:31
pointClouds:
- iD: 1
  position:
    x: 0.07
    y: 1.62
    z: 0.84
  rotation:
    x: 44.77001
    y: 185.25
    z: 4.967257
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.0
  depthMin: 1
  clampXMin: 0.3
  clampXMax: 0.7
  clampYMin: 0.3
  clampYMax: 0.96
- iD: 2
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
  clampXMin: 0
  clampXMax: 1
  clampYMin: 0
  clampYMax: 1
