configName: 1PP
createdAt: 2026-04-23 15:35:05
lastModified: 2026-08-06 14:11:39
pointClouds:
- iD: 1
  position:
    x: -0.13
    y: 1.64
    z: 1.24
  rotation:
    x: 44.60535
    y: 171.25
    z: 356.7675
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 3
  depthMin: 1
  clampXMin: 0.3
  clampXMax: 0.7
  clampYMin: 0.3
  clampYMax: 0.96
  referencePoint:
    x: 0.05358155
    y: 0.009859324
    z: 1.502176
- iD: 2
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
  clampXMin: 0
  clampXMax: 1
  clampYMin: 0
  clampYMax: 1
  referencePoint:
    x: 0
    y: 0
    z: 0
