configName: 3PP - Back
createdAt: 2026-06-11 14:02:46
lastModified: 2026-08-06 14:21:40
pointClouds:
- iD: 1
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
  clampXMin: 0
  clampXMax: 1
  clampYMin: 0
  clampYMax: 1
  referencePoint:
    x: 0
    y: 0
    z: 0
- iD: 2
  position:
    x: 0.12
    y: 0.9899999
    z: -1.64
  rotation:
    x: 8.99
    y: 2.45
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 2.25
  depthMin: 0
  clampXMin: 0.3
  clampXMax: 0.7
  clampYMin: 0.05
  clampYMax: 1
  referencePoint:
    x: -0.0765181
    y: -0.2242815
    z: 1.846088
