configName: 3PP
createdAt: 2026-06-11 14:02:46
lastModified: 2026-08-06 14:19:02
pointClouds:
- iD: 1
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
  clampXMin: 0
  clampXMax: 1
  clampYMin: 0
  clampYMax: 1
  referencePoint:
    x: 0
    y: 0
    z: 0
- iD: 2
  position:
    x: 0.09
    y: 0.98
    z: -0.09999999
  rotation:
    x: 8.99
    y: 2.45
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 2.25
  depthMin: 0
  clampXMin: 0.3
  clampXMax: 0.7
  clampYMin: 0.05
  clampYMax: 1
  referencePoint:
    x: -0.1561865
    y: -0.04560918
    z: 1.615445
