configName: Mirror - Flip
createdAt: 2026-06-18 10:41:48
lastModified: 2026-08-06 14:17:03
pointClouds:
- iD: 1
  position:
    x: 0.17
    y: 1.6
    z: 0.35
  rotation:
    x: 44.27001
    y: 350.78
    z: 353.09
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 3
  depthMin: 0
  clampXMin: 0.3
  clampXMax: 0.7
  clampYMin: 0.04598596
  clampYMax: 0.9524282
  referencePoint:
    x: 0.0363569
    y: 0.0195266
    z: 1.362025
- iD: 2
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
  clampXMin: 0
  clampXMax: 1
  clampYMin: 0
  clampYMax: 1
  referencePoint:
    x: 0
    y: 0
    z: 0
