configName: Mirror
createdAt: 2026-06-11 13:58:00
lastModified: 2026-07-14 09:36:57
pointClouds:
- iD: 1
  position:
    x: -0.01
    y: 1.57
    z: 0.39
  rotation:
    x: 41.57001
    y: 5.53
    z: 4.65756
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.0
  depthMin: 1
  clampXMin: 0.3
  clampXMax: 0.7
  clampYMin: 0.3
  clampYMax: 0.96
- iD: 2
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
  clampXMin: 0
  clampXMax: 1
  clampYMin: 0
  clampYMax: 1
