configName: 1PP - Flip
createdAt: 2026-04-23 15:35:05
lastModified: 2026-07-07 08:32:10
stimulusDisplay:
  position:
    x: 0
    y: 0.9
    z: 2
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  backgroundColor:
    r: 0
    g: 0
    b: 0
    a: 1
pointClouds:
- iD: 1
  position:
    x: 0.07
    y: 1.62
    z: 1.28
  rotation:
    x: 44.57001
    y: 186.81
    z: 1.840001
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 2.537773
  depthMin: 1.235421
  clampXMin: 0.3427096
  clampXMax: 1
  clampYMin: 0
  clampYMax: 1
- iD: 2
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 1.411696
  depthMin: 0.4647805
  clampXMin: 0
  clampXMax: 1
  clampYMin: 0
  clampYMax: 1
