configName: demoNoM_1PP - Flip
createdAt: 2026-04-23 15:35:05
lastModified: 2026-06-11 13:56:27
stimulusDisplay: 
pointClouds:
- iD: 1
  position:
    x: 0.12
    y: 1.32
    z: 2.44
  rotation:
    x: 44.57001
    y: 186.81
    z: 1.840001
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 2.537773
  depthMin: 1.235421
  clampXMin: 0.3277366
  clampXMax: 0.7318519
  clampYMin: 0
  clampYMax: 1
- iD: 2
  position:
    x: 920.2986
    y: 542.8495
    z: 0.607
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
  clampXMin: 0
  clampXMax: 1
  clampYMin: 0
  clampYMax: 1
