configName: 1PP
createdAt: 2026-04-23 15:35:05
lastModified: 2026-06-11 15:39:46
stimulusDisplay: 
pointClouds:
- iD: 1
  position:
    x: -0.32
    y: 1.13
    z: 2.37
  rotation:
    x: 45.90378
    y: 171.23
    z: 356.7675
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 2.537773
  depthMin: 1.235421
  clampXMin: 0.3277366
  clampXMax: 0.7318519
  clampYMin: 0
  clampYMax: 1
- iD: 2
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
  clampXMin: 0
  clampXMax: 1
  clampYMin: 0
  clampYMax: 1
