configName: 1PP
createdAt: 2026-05-07 14:14:56
lastModified: 2026-06-05 10:26:41
stimulusDisplay:
  position:
    x: 0.4650241
    y: 1.713383
    z: 1.932
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  backgroundColor:
    r: 0
    g: 0
    b: 0
    a: 1
pointClouds:
- iD: 1
  position:
    x: -0.421463
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0.7415771
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 2.895776
  depthMin: 1.380649
  clampXMin: 0.3838222
  clampXMax: 0.7885255
  clampYMin: 0.4523989
  clampYMax: 0.9516402
- iD: 2
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 3.883522
  depthMin: 0
  clampXMin: 0
  clampXMax: 0.7225603
  clampYMin: 0
  clampYMax: 1
