configName: 3PP - Back
createdAt: 2026-06-11 14:02:46
lastModified: 2026-07-07 08:34:27
stimulusDisplay:
  position:
    x: 0
    y: 0.9
    z: 0.5
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  backgroundColor:
    r: 0
    g: 0
    b: 0
    a: 1
pointClouds:
- iD: 1
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
  clampXMin: 0
  clampXMax: 1
  clampYMin: 0
  clampYMax: 1
- iD: 2
  position:
    x: 0
    y: 0.9899999
    z: -1.66
  rotation:
    x: 8.99
    y: 2.45
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 2.27823
  depthMin: 0
  clampXMin: 0.2204771
  clampXMax: 0.7139753
  clampYMin: 0
  clampYMax: 1
