configName: bruno2
createdAt: 2026-04-02 15:30:22
lastModified: 2026-05-15 14:48:24
uICanvas:
  position:
    x: 0
    y: 1
    z: 2
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  backgroundColor:
    r: 0
    g: 0
    b: 0
    a: 0.819679
pointClouds:
- iD: 1
  position:
    x: 0
    y: 1
    z: 0.607
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 0.3428572
  depthMin: 0
  clampXMin: 0
  clampXMax: 1
  clampYMin: 0
  clampYMax: 1
- iD: 2
  position:
    x: -0.85
    y: 0.76
    z: 0.607
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
  clampXMin: 0
  clampXMax: 1
  clampYMin: 0
  clampYMax: 1
- iD: 0
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 0.5808365
  depthMin: 0.3657073
  clampXMin: 0.4913839
  clampXMax: 0.414946
  clampYMin: 0.5321932
  clampYMax: 0.6417934
