configName: Bruno
createdAt: 2026-04-02 15:20:45
lastModified: 2026-04-02 15:30:03
pointClouds:
- iD: 1
  position:
    x: 0
    y: 1
    z: 0.36
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
- iD: 2
  position:
    x: 0
    y: 1.97
    z: 0.97
  rotation:
    x: 53.51
    y: 180
    z: 0
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0.1
