configName: Bruno
createdAt: 2026-04-02 15:20:45
lastModified: 2026-04-30 15:17:42
pointClouds:
- iD: 1
  position:
    x: 0.09
    y: 1.8
    z: 1.67
  rotation:
    x: 53.17001
    y: -8.901742E-08
    z: 1.42
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0.6081063
- iD: 2
  position:
    x: -0.12
    y: 1.07
    z: 0.93
  rotation:
    x: 10.99
    y: 0
    z: -1.085851E-07
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0.6262228
