configName: Bruno
createdAt: 2026-04-02 15:20:45
lastModified: 2026-05-08 15:00:23
uICanvas:
  position:
    x: 0
    y: 0.84
    z: 2
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  backgroundColor:
    r: 0
    g: 0
    b: 0
    a: 0.7
pointClouds:
- iD: 2
  cameraPosition: 
  cameraRotation: 
  position:
    x: 0
    y: 1.1
    z: 0.17
  rotation:
    x: 12.5
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 2.5
  depthMin: 1.264349
  clampXMin: 0.1302839
  clampXMax: 0.7164412
  clampYMin: 0
  clampYMax: 1
- iD: 1
  cameraPosition: 
  cameraRotation: 
  position:
    x: 0
    y: 1.1
    z: 1
  rotation:
    x: 12.5
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 2.65431
  depthMin: 1.264349
  clampXMin: 0.2760581
  clampXMax: 0.8161816
  clampYMin: 0.2915484
  clampYMax: 1
