configName: demoNoM_1PP
createdAt: 2026-04-23 15:35:05
lastModified: 2026-04-30 11:23:17
pointClouds:
- iD: 1
  position:
    x: 0.03
    y: 1.21
    z: 1.62
  rotation:
    x: 35.76
    y: 186.16
    z: 0.8
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 2.656951
  depthMin: 1.175833
- iD: 2
  position:
    x: 920.2986
    y: 542.8495
    z: 0.607
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
