configName: demoNoM_1PP_flip
createdAt: 2026-04-23 15:44:28
lastModified: 2026-04-23 15:46:55
pointClouds:
- iD: 1
  position:
    x: 1.650024
    y: 1.900024
    z: 1.6
  rotation:
    x: 35.76
    y: 175.95
    z: 0.8
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 2.412393
  depthMin: 1.073665
- iD: 2
  position:
    x: 920.2986
    y: 542.8495
    z: 0.607
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
