configName: demoNoM_mirrorself
createdAt: 2026-04-23 15:32:39
lastModified: 2026-04-23 15:34:50
pointClouds:
- iD: 1
  position:
    x: 1.780029
    y: 1.700012
    z: 1.22
  rotation:
    x: 35.76
    y: 355.16
    z: 0.7999998
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 2.036602
  depthMin: 0
- iD: 2
  position:
    x: 920.2986
    y: 542.8495
    z: 0.607
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
