configName: demoNoM_FBI
createdAt: 2026-04-23 15:47:09
lastModified: 2026-04-23 15:56:39
pointClouds:
- iD: 1
  position:
    x: -33.92999
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
- iD: 2
  position:
    x: 1.700012
    y: 1
    z: 0.73
  rotation:
    x: 20.96
    y: 5.130001
    z: 4.38
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 2.615829
  depthMin: 0
