configName: demoNoM
createdAt: 2026-04-23 15:07:55
lastModified: 2026-04-23 15:23:24
pointClouds:
- iD: 1
  position:
    x: 1.780029
    y: 1.700012
    z: 1.22
  rotation:
    x: 35.76
    y: 4.94
    z: 0.8
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 1.877412
  depthMin: 0.9990365
- iD: 2
  position:
    x: 920.2986
    y: 542.8495
    z: 0.607
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
