configName: interpolation
createdAt: 2026-04-23 09:03:32
lastModified: 2026-04-23 13:43:03
pointClouds:
- iD: 1
  position:
    x: -0.5
    y: 1
    z: 0.607
  rotation:
    x: 0
    y: 0
    z: 75.89999
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
- iD: 2
  position:
    x: 0
    y: 1
    z: 0.607
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
