configName: Mirror - Flip
createdAt: 2026-06-18 10:41:48
lastModified: 2026-07-14 09:34:51
stimulusDisplay:
  position:
    x: 0
    y: 0.9
    z: 2
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  backgroundColor:
    r: 0
    g: 0
    b: 0
    a: 1
pointClouds:
- iD: 1
  position:
    x: 0.17
    y: 1.6
    z: 0.35
  rotation:
    x: 44.27001
    y: 350.78
    z: 353.09
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 2.845935
  depthMin: 0.5105983
  clampXMin: 0.2581356
  clampXMax: 0.7418642
  clampYMin: 0
  clampYMax: 1
- iD: 2
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
  clampXMin: 0
  clampXMax: 1
  clampYMin: 0
  clampYMax: 0.1561171
