configName: Mirror
createdAt: 2026-06-11 13:58:00
lastModified: 2026-07-07 08:35:20
stimulusDisplay:
  position:
    x: 0
    y: 0.9
    z: 2
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  backgroundColor:
    r: 0
    g: 0
    b: 0
    a: 1
pointClouds:
- iD: 1
  position:
    x: -0.01
    y: 1.57
    z: 0.39
  rotation:
    x: 41.57001
    y: 5.440005
    z: 4.65756
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 2.438245
  depthMin: 0.7150617
  clampXMin: 0.3406713
  clampXMax: 0.7020844
  clampYMin: 0
  clampYMax: 1
- iD: 2
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
  clampXMin: 0
  clampXMax: 1
  clampYMin: 0
  clampYMax: 1
