configName: okjn
createdAt: 2026-03-26 15:20:07
lastModified: 2026-03-26 15:20:16
pointClouds:
- iD: 1
  position:
    x: 0
    y: 1
    z: 0.607
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
- iD: 2
  position:
    x: 0
    y: 1
    z: 0.607
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0
