configName: test
createdAt: 2026-03-26 14:15:29
lastModified: 2026-03-26 14:15:37
pointClouds:
- iD: 1
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 3
  depthMin: 0.1
  flipX: false
  flipY: false
- iD: 2
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  depthMax: 3
  depthMin: 0.1
  flipX: false
  flipY: false
