configName: testlyksnfkajsn
createdAt: 2026-03-26 15:07:44
lastModified: 2026-03-26 15:08:12
pointClouds:
- iD: 1
  position:
    x: 0
    y: 1.23
    z: 0.38
  rotation:
    x: 350.77
    y: 16.15
    z: 275.77
  scale:
    x: -1
    y: 1
    z: 1
  depthMax: 3.47
  depthMin: 0.4120876
- iD: 2
  position:
    x: 0.23
    y: 1.23
    z: 0.607
  rotation:
    x: 4.85
    y: 351
    z: 292.62
  scale:
    x: 1
    y: -1
    z: 1
  depthMax: 3.47
  depthMin: 0
